name: aegis_hub_mobile
description: Aegis Hub disaster response mobile client.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.8.0+1
  uuid: ^4.5.1
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  connectivity_plus: ^6.1.0
  battery_plus: ^6.2.1
  image_picker: ^1.1.2
  record: ^5.2.0
  path_provider: ^2.1.5
  universal_io: ^2.2.2
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  http_parser: ^4.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/runtime_config.json
